name: Rebuild Vite Assets

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Build
      run: |
        npm install
        npm run build

    - uses: EndBug/add-and-commit@v9
      with:
          message: 'chore(deps): rebuild vite assets'
          committer_name: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com
